version: '3.2'

services:
  db:
    image: mariadb:10.3.13
    env_file: ./.env
    ports:
      - '33006:3306'
    environment:
      MYSQL_USER: csteam
      MYSQL_DATABASE: csteam
    volumes:
      - data:/var/lib/mysql
volumes:
  data:
